name: "get-node-active-major-versions"
author: "Masaya Suzuki"
description: "GitHub Actions to get Node.js LTS and maintenance major versions."
outputs:
  versions:
    description: "Node.js LTS and maintenance major version"
    value: ${{ steps.get_versions.outputs.result }}
runs:
  using: "composite"
  steps:
    - name: Get versions
      id: get_versions
      uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7.1.0
      with:
        script: |
          const {script} = require('${{ github.action_path }}/dist/get-version.js')
          return await script()
