name: "get-node-active-major-versions"
author: "Masaya Suzuki"
description: "GitHub Actions to get Node.js LTS and maintenance major versions."
outputs:
  versions:
    description: "Node.js LTS and maintenance major version"
    value: ${{ steps.get_versions.outputs.result }}
runs:
  using: "composite"
  steps:
    - name: Get versions
      id: get_versions
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      with:
        script: |
          const {script} = require('${{ github.action_path }}/dist/get-version.js')
          return await script()
